remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

title: 8410-subreddit-sentiment-analysis
description: Computational text processing project using NLP libraries such as spaCy and nltk for entitiy recognition and sentiment analysis, respectively.

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Read me
    link: ./index.html
  - name: Jupyter notebook
    link: ./dmir-8410